### ISSUE TITLE
 run the .php file

### ISSUE THREAD

**Issue by ale07alvarez** [decodebiology/geneSCF#4]
Hi,
I downloaded the software 
downloads.php
I'm not sure how to open or run the .php file.

**Comment by santhilalsubhash** [comment]
Hello,

Did you try downloading from geneSCF home page ? http://genescf.kandurilab.org/downloads.php

**Comment by ale07alvarez** [comment]
Yes,
I get this file:
download-v1.1-p2.php

**Comment by santhilalsubhash** [comment]
Do not right-click and save from link. You have to click the Download link.

**Comment by santhilalsubhash** [comment]
If you are downloading using command line use the following link,

http://genescf.kandurilab.org/ftp/geneSCF-master-v1.1-p2.tar.gz

Example: 

`wget http://genescf.kandurilab.org/ftp/geneSCF-master-v1.1-p2.tar.gz`
