### ISSUE TITLE
Error: Illegal division by zero at List.pl line 599, <IN2> chunk 1

### ISSUE THREAD

**Issue by golrokh51** [decodebiology/geneSCF#5]
command line: ./geneSCF -m=normal -i=/Users/.../.../geneID_list.txt -t=gid -o=simple1_CSF.txt -db=GO_all -p=yes -bg=24850 -org=mgi 

**ERROR:
processing in 'normal' mode started....Fri  9 Nov 2018 17:31:39 EST
=> Finished retriving database...
=> Calculating statistics...
find: -printf: unknown primary or operator
Note:Only KEGG and Geneontology supports multiple organisms (GeneSCF-xx/org_codes_help). If you choose REACTOME/NCG database please specify organism as 'Hs'. Currently REACTOME and NCG in GeneSCF only supports Human (Hs).
GO_all last updated 
Illegal division by zero at /Users/.../.../geneSCF-master-source-v1.1-p2/class/lib/List/Vectorize/lib/List.pl line 599, <IN2> chunk 1.
Fri  9 Nov 2018 17:31:40 EST finished processing**

**Comment by decodebiology** [comment]
Which operating system are you using ?

Requirement:
GeneSCF only works on Linux system, it has been successfully tested on Ubuntu, Mint,Cent OS and Windows 10 bash (>version 1607). Other distributions of Linux might work as well.

**Comment by decodebiology** [comment]
Since you did not respond back. I assume above comment answered you query. I am closing this issue now. Thanks for using GeneSCF.
