### ISSUE TITLE
unable to update GO database files

### ISSUE THREAD

**Issue by univerchen** [decodebiology/geneSCF#6]
I tried to update GO database, but failed. 
command line: ./prepare_database -db=GO_all -org=goa_human

The error is 
gzip: /***/geneSCF-master-source-v1.1-p2/class/lib/db/goa_human/gene_association.goa_human.gz: unexpected end of file
cat: /***/geneSCF-master-source-v1.1-p2/class/lib/db/goa_human/gene_association.goa_human: No such file or directory
cat: /***/geneSCF-master-source-v1.1-p2/class/lib/db/goa_human/gene_association.goa_human: No such file or directory
Updating gene information...
Do not panic. The processing is going on...
rm: cannot remove '/***/geneSCF-master-source-v1.1-p2/class/lib/db/goa_human/gene_association.goa_human': No such file or directory
Database retreived..You are now ready to use geneSCF with organism goa_human from --database GO
Done....

The annotation files, like GO_all_gid.txt, is blank and 0 bytes.
I use this in ubuntu 16.04. It works fine to update KEGG database. Does anyone know how to fix this?
Thanks a lot.

**Comment by decodebiology** [comment]
Hello univerchen,

Thanks for reporting the error. 

Due to changes in HTTP's request and response code, GeneSCF has to undergo some minor changes in the some of the modules. Downloading updated version (recently updated) solves issues related to database retrieval (prepare_database module).

Let me know if it solves your error.

**Comment by univerchen** [comment]
Hello!
Thanks for your reply.
I downloaded the newest version just now, and it works fine now.
Thanks again!

**Comment by decodebiology** [comment]
Good to hear. Now I will close this issue. Feel free to report if there are any further issues in future. Thanks for using GeneSCF.
