### ISSUE TITLE
GeneSCF - Error opening input file and Illegal division by zero

### ISSUE THREAD

**Issue by EllieAdib** [decodebiology/geneSCF#7]
Hello,

I have been trying to use GeneSCF v1.1 and have faced issues from the beginning. Now, I can easily run the test provided by the package but I cannot open my own gene list file.
Initially I had this file made in a text file using windows excel/ or saving from R as a text file. I noticed the problem of CRFL in windows and FL endings in linux, so I made my list using Gedit, I also converted my original list using dos2unix to have a unix formatted text file. But, I am unable to open my input file and I get the following error whether I use the update mode or normal mode after preparing the database.

>> ~/GSF/geneSCF-master-source-v1.1-p2# ./geneSCF -m=normal -i=test/DEG.list -o=~/GSF/output/ -t=sym -db=GO_MF -bg=20000 --plot=yes -org=mgi
processing in 'normal' mode started....Sat Oct 12 16:45:41 EDT 2019
=> Finished retriving database...
=> Calculating statistics...
Note:Only KEGG and Geneontology supports multiple organisms (GeneSCF-xx/org_codes_help). If you choose REACTOME/NCG database please specify organism as 'Hs'. Currently REACTOME and NCG in GeneSCF only supports Human (Hs).
GO_MF last updated 2019-10-12 16:20

***
Error opening input file: test/DEG.list
***

Illegal division by zero at /root/GSF/geneSCF-master-source-v1.1-p2/class/lib/List/Vectorize/lib/List.pl line 599.
Sat Oct 12 16:45:42 EDT 2019 finished processing

I also need to add that I use ubuntu on a windows machine.

Can anyone help me figure out the problem.

**Comment by decodebiology** [comment]
Just to check. Did you follow these steps while converting it to UNIX text format from excel?

1) Open your excel having the list. Copy the list (by only selecting the column containing the list)

2) Open GEDIT for windows or GEDIT from UBUNTU. Paste the copied list and save it as '.txt' file

This usually solves the issue. 

If it is not, there is a possibility that none of your genes from your list matches the database (which is usually rare). Can you please attach the input file?

**Comment by EllieAdib** [comment]
I think I did the second option. I have attached the input file here.
[DEG.txt](https://github.com/decodebiology/geneSCF/files/3721900/DEG.txt)

**Comment by decodebiology** [comment]
Attached list tested and works fine. Try updating the database and run GeneSCF again. I used following steps with freshly downloaded GeneSCF.

`./prepare_database -db=GO -org=mgi`

```
Downloading GO database....
Extracting mgi information...
Updating gene information...
Do not panic. The processing is going on...
Database retreived..You are now ready to use geneSCF with organism mgi from --database GO
Done....Sun Oct 13 18:19:22 CEST 2019
```
`./geneSCF -m=normal -i=../DEG.txt -o=./ -t=sym -db=GO_MF -bg=20000 --plot=yes -org=mgi
`
```
processing in 'normal' mode started....Sun Oct 13 18:19:48 CEST 2019
=> Finished retriving database...
=> Calculating statistics...
Note:Only KEGG and Geneontology supports multiple organisms (GeneSCF-xx/org_codes_help). If you choose REACTOME/NCG database please specify organism as 'Hs'. Currently REACTOME and NCG in GeneSCF only supports Human (Hs).
GO_MF last updated 2019-10-13 18:17
nohup: redirecting stderr to stdout
=================
Run successful. Check your output directory ./
=================
```

**Comment by EllieAdib** [comment]
It is very strange, I still get the same error. I am going to try reinstalling the software and go from there.

**Comment by EllieAdib** [comment]
My problem is solved after reinstalling the GensSCF.
Thank you for the time you put :)

**Comment by decodebiology** [comment]
Good to hear that your problem is resolved. Come back if you have more questions about GeneSCF. And please don't forget to cite GeneSCF, if you are using it for your research purposes.

**Comment by EllieAdib** [comment]
For sure, I will cite it. I have one last question, the output of GeneSCF is a tsv file and it can also plot it for you and I added the argument of plot=yes but I never receive the plot after running it. Do I need to do anything special?

 ./geneSCF -m=normal -i=../DEG.txt -o=./ -t=sym -db=GO_CC -bg=20000 --plot=yes -org=mgi
processing in 'normal' mode started....Sun Oct 13 14:02:58 EDT 2019
=> Finished retriving database...
=> Calculating statistics...
Note:Only KEGG and Geneontology supports multiple organisms (GeneSCF-xx/org_codes_help). If you choose REACTOME/NCG database please specify organism as 'Hs'. Currently REACTOME and NCG in GeneSCF only supports Human (Hs).
GO_CC last updated 2019-10-13 13:54
nohup: redirecting stderr to stdout
=================
Run successful. Check your output directory ./
=================

Parameters used:

Organism:               mgi
background genes:       20000
Identitiy:              Gene Symbol
Database used:          GO_CC
Output file:            ./DEG.txt_GO_CC_functional_classification.tsv
                WARNING: Your output is not sorted with P-val/FDR.

**Comment by decodebiology** [comment]
For bubble plot with three different formats PNG, SVG and PDF.
Note: Plots required 'ggplot2' to be installed on the system. If specified --plot=yes and you cannot find the plots, means R package or 'ggplot2' is not available in your system.

**Comment by EllieAdib** [comment]
Thanks! 
My confusion arised due to having Rstudion both on windows and on ubunto, yet having ggplot library installed on one :'). Thank for your help

**Comment by decodebiology** [comment]
You just need to have 'R-cran (installed ggplot2)' to be at systems PATH. It will work.

**Comment by decodebiology** [comment]
Hope everything is resolved. I am closing this issue now.
