### ISSUE TITLE
Unable to run geneSCF on linux 

### ISSUE THREAD

**Issue by yxu405** [decodebiology/geneSCF#8]
When I ran geneSF using this command, it gives me this error message. 
Command:
./geneSCF -m=normal -i=test/annotation.tsv -o=test/output/ -t=sym -db=GO_MF -bg=20000 --plot=yes -org=goa_human
Message:
processing in 'normal' mode started....Sun May 24 08:41:35 PDT 2020
=> Finished retriving database...
=> Calculating statistics...
Note:Only KEGG and Geneontology supports multiple organisms (GeneSCF-xx/org_codes_help). If you choose REACTOME/NCG database please specify organism as 'Hs'. Currently REACTOME and NCG in GeneSCF only supports Human (Hs).
GO_MF last updated 2017-07-07 14:04
nohup: redirecting stderr to stdout

Run successful. Check your output directory test/output/ 

Parameters used:

Organism:		Human/Homo sapiens
background genes:	20000
Identitiy:		Gene Symbol
Database used:		GO_MF
Output file:		test/output/annotation.tsv_GO_MF_functional_classification.tsv
		WARNING: Your output is not sorted with P-val/FDR.

---------------------

Author: Santhilal Subhash
santhilal.subhash@gu.se
GeneSCF elapse time 6 seconds
Sun May 24 08:41:41 PDT 2020 finished processing

Furthermore, because I saw your previous post about the getting such error could due to database not being updated. Then, I tried using this command to update the database. 
Command:./prepare_database -db=[GO_all|GO_BP|GO_MF|GO_CC|KEGG|REACTOME] -org=[hsa]
Message: 
KEGG: command not found
GO_CC: command not found
REACTOME]: command not found
GO_MF: command not found
GO_BP: command not found

Please help! Thank you so much for your time

**Comment by decodebiology** [comment]
Will you please provide your sample input file?

**Comment by yxu405** [comment]
Sure! 
![Screen Shot 2020-05-24 at 11 27 25 AM](https://user-images.githubusercontent.com/52365451/82761741-8edf6a00-9db1-11ea-8fca-60ca9404a550.png)

**Comment by decodebiology** [comment]
Hi,

Listed identifiers ae protein IDs. GeneSCF only accepts Gene symbol (HGNC) or Entrez gene IDs.

Example:

'A0A023HHK9' can be given as either 'TET1' (HGNC) or '80312' (Entrez).

**Comment by yxu405** [comment]
I know this is an easy question to ask, I am pretty new at using this, but is there any way that I can convert this list of annotations to gene IDs? The list I obtained from, QuickGo, wouldn't show me the gene IDs in group; as I had to click in one by one.

**Comment by decodebiology** [comment]
You must convert 'UniProt Accession' to 'Gene Symbols' or 'Entrez Gene ID' or 'HGNC symbols'. Check out if this helps, https://www.biostars.org/p/283347/

Good luck.

**Comment by decodebiology** [comment]
I will be closing this issue now. You are welcome to contact me for future queries.
